add logic for working out the source branch value to use from github envs

diff --git a/actions/branch-name/action.yml b/actions/branch-name/action.yml
--- a/actions/branch-name/action.yml
+++ b/actions/branch-name/action.yml
@@ -31,7 +31,7 @@ outputs:
 runs:
   using: composite
   steps:
-    ####### BUILD THE BINARY #######
+    ####### BUILD THE BINARY
     # get root directory of this action
     - name: "Setup directories"
       id: directories
@@ -62,20 +62,46 @@ runs:
       env:
         source: "${{ steps.directories.outputs.cmd_directory }}/branch-name"
         binary: "${{ steps.directories.outputs.BUILD_DIRECTORY }}/branch-name"
-        # TODO: disable cgo
+        # TODO: decide about cgo usage
       # TODO: remove echo
       run: |
         echo 'go build -ldflags="-w -s" -o ${{ env.binary }} ${{ env.source }}/'
-    ####### END BUILD #######
-    ####### GET ENV VALUES #######
+    ####### END BUILD
+    ####### RUN COMMAND
+    # get the base branch name
     - name: "Get branch name from input or environment"
+      id: branch
       if: ${{ inputs.name == '' }}
       shell: bash
       env:
         from_input: ${{ inputs.name }}
         from_pull_request: ${{ github.head_ref }}
         from_push: ${{ github.ref_name }}
+      # push in order of precedence which value to use as the branch name
       run: |
-        echo "FROM_INPUT=${{ env.from_input }}"
-        echo "FROM_PULL_REQUEST=${{ env.from_pull_request }}"
-        echo "FROM_PUSH=${{ env.from_push }}"
+        if [ "${{ env.from_input }}" != "" ]; then
+          echo "INPUT=${{ env.from_input }}"
+          echo "BRANCH=${{ env.from_input }}" >> $GITHUB_OUTPUT
+        elif [ "${{ env.from_pull_request }}" != "" ]; then
+          echo "PULL_REQUEST=${{ env.from_pull_request }}"
+          echo "BRANCH=${{ env.from_pull_request }}" >> $GITHUB_OUTPUT
+        elif [ "${{ env.from_push }}" != "" ]; then
+          echo "PUSH=${{ env.from_push }}"
+          echo "BRANCH=${{ env.from_push }}" >> $GITHUB_OUTPUT
+        done
+    # run the command if the branch name is set
+    - name: "Generate safe branch name"
+      id: cmd
+      if: ${{ steps.branch.outputs.BRANCH != '' }}
+      shell: bash
+      env:
+        cmd: "${{ steps.directories.outputs.BUILD_DIRECTORY }}/branch-name"
+        branch: ${{ steps.branch.outputs.BRANCH != '' }}
+      run: |
+        echo "branch=${{ env.branch }}"
+    # fail if branch is empty
+    - name: "Fail on empty branch"
+      if: ${{ steps.branch.outputs.BRANCH == '' }}
+      shell: bash
+      run: |
+        exit 1
