update branch-name

diff --git a/.github/actions/branch-name/action.yml b/.github/actions/branch-name/action.yml
--- a/.github/actions/branch-name/action.yml
+++ b/.github/actions/branch-name/action.yml
@@ -21,120 +21,83 @@ outputs:
 runs:
   using: "composite"
   steps:
-    # Create environment variables for the action repo data and workspace
-    # directories and convert those into step outputs for use in other 
-    # steps
-    - name: "Environment variables to step variables"
-      id: gha
+    # Check running as a remote call
+    - name: "Ensure running as remote"
+      if: ${{ github.action_ref == '' }}
       shell: bash
-      env: 
-        GHA_REPO: "${{ github.action_repository }}"
-        GHA_REF: "${{ github.action_ref }}"
-        GHA_PATH: "${{ github.workspace }}/opg-gha"    
-      run: |        
-        echo -e "Environment variables to step variables"
-        echo "repo=${GHA_REPO}" >> $GITHUB_OUTPUT
-        echo "ref=${GHA_REF}" >> $GITHUB_OUTPUT
-        echo "path=${GHA_PATH}" >> $GITHUB_OUTPUT
-        echo "isSelf=${{ github.repository == 'ministryofjustice/opg-github-actions' }}" >> $GITHUB_OUTPUT
-    # If we aren't being called from ourselves, then checkout the repository
-    # at the commit we know of into the new path
-    - name: "Checkout action [ ${{ steps.gha.outputs.isSelf }} ]"
-      uses: actions/checkout@v4
-      if: ${{ steps.gha.outputs.isSelf != 'true' }}
-      with:
-        repository: ${{ steps.gha.outputs.repo }}
-        ref: ${{ steps.gha.outputs.ref }}
-        path: ${{ steps.gha.outputs.path }}
-    
-    # If the repository property matches our own name (so a call from itself)
-    # then we dont checkout anything, set the path to be from the 
-    # base of self and show the last commit hash and message for debug
-    #
-    # If its called remotely, then checkout self into a subfolder of the
-    # workspace and presume can use the env variables from the 'gha' step
-    - name: "Set directory path"
-      id: setPath
-      shell: bash      
+      run: |
+        err="ERROR: this composite action must be run via full path (eg ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.3.1)"
+        echo -e "${err}"
+        echo -e "${err}" >&2
+        echo -e "${err}" >> $GITHUB_STEP_SUMMARY
+        exit 1
+    # Use bash shell script to fetch and work out releases    
+    - name: "Get release binary for this runner"
+      shell: bash
+      id: fetch
       env:
-        JSON_DEBUG: ${{ toJSON(github) }}
-      run: | 
-        echo -e "Set directory path"
-        set -e 
-        if [ "${{ steps.gha.outputs.isSelf }}" == "true" ]; then 
-          echo -e "Warning: running against self."
-          echo -e "Using this commit:"
-          git log -n1 --format="oneline"          
-
-          appPath="${{ github.workspace }}"
-        elif [ -n "${{ steps.gha.outputs.ref}}" ]; then   
-          echo -e "Running from remote workflow"       
-          appPath="${{ steps.gha.outputs.path }}"
-        else
-          echo -e "ERROR: failed to determine location of go code"
-          echo -e "ERROR: failed to determine location of action code" >> $GITHUB_STEP_SUMMARY
-          echo "${JSON_DEBUG}"             
-          exit 1
-        fi        
-        echo -e "appPath=${appPath}"
-        echo "appPath=${appPath}" >> $GITHUB_OUTPUT
-        
-        if [ "${{ runner.debug }}" == "1" ]; then
-          ls -la ${appPath}/go/
+        GH_TOKEN: ${{ github.token }}
+        GH_ACTION_REPOSITORY: "${{ github.action_repository }}"
+        GH_ACTION_REF: "${{ github.action_ref }}"
+        GH_WORKSPACE: "${{ github.workspace }}"
+        actionsRootDir: "${{ github.action_path }}/../"
+      run: |
+        echo -e "Get release binary"
+        cd ${actionsRootDir}
+        ./release-download.sh 2> $GITHUB_STEP_SUMMARY
+    ## LOCAL BUILD
+    # setup and build locally if the release data is not setup
+    - name: "Setup go"
+      uses: actions/setup-go@v4
+      if: ${{ steps.fetch.outputs.RELEASE == '' }}
+      with:
+        go-version-file: '${{ steps.fetch.outputs.SELF_BUILD }}/./go/go.mod'
+        cache: false
+    - name: Build directly from source
+      id: buildFromSource
+      if: ${{ steps.fetch.outputs.RELEASE == '' }}
+      shell: bash
+      env:
+        buildSource: '${{ steps.fetch.outputs.SELF_BUILD }}'
+        target: '${{ steps.fetch.outputs.TARGET_BUILD }}'
+      run: |
+        echo -e "Build from source"
+        cd ${buildSource}
+        echo -e "Building (with make) for ${target}"        
+        make release
+        release="${buildSource}/go/builds/${target}"
+        echo -e "RELEASE=${release}"
+        echo "RELEASE=${release}" >> $GITHUB_OUTPUT
+    ## DETERMINE BINARY PATH
+    - name: "Determine binary to use"
+      id: binary
+      shell: bash
+      env:
+        direct: ${{ steps.fetch.outputs.RELEASE }}
+        built: ${{ steps.buildFromSource.outputs.RELEASE }}
+      run: |
+        binary=""
+        if [ "${direct}" != "" ]; then
+          binary="${direct}"
+        elif [ "${built}" != "" ]; then
+          binary="${built}"
         fi
-    # Setup go
-    - uses: actions/setup-go@v4
-      with:
-        go-version-file: '${{ steps.setPath.outputs.appPath }}/go/go.mod'        
-        cache-dependency-path: |
-          ${{ steps.setPath.outputs.appPath }}/go/go.sum
-    - shell: bash
-      run: go version
-    # Get os & arch name for make target
-    - name: "Build info"
-      id: info
-      shell: bash
-      run: |
-        echo -e "Build info"
-        gha_os=$(uname | tr '[:upper:]' '[:lower:]')
-        gha_arc=$(uname -m)
-        make_target="${gha_os}_${gha_arc}"
-        binpath="${{ steps.setPath.outputs.appPath }}/go/builds/${make_target}"
-        echo "target=${make_target}" >> $GITHUB_OUTPUT
-        echo "binpath=${binpath}" >> $GITHUB_OUTPUT
-
-        if [ -a "${binpath}" ]; then
-          echo "Build file exists."
-          echo "binexists=true" >> $GITHUB_OUTPUT
-        else 
-          echo "Build file does not exist."
-          echo "binexists=false" >> $GITHUB_OUTPUT
-        fi        
-    # This will build the app using the makefile to generate
-    #   ./build/$target/main
-    # which can then be run
-    - name: "Build app [ ${{ steps.info.outputs.binexists == 'false' }} ]"
-      id: build      
-      shell: bash
-      if: ${{ steps.info.outputs.binexists == 'false' }}
-      env:
-        target: '${{ steps.info.outputs.target }}'
-      run: |
-        echo -e "Build app"
-        cd ${{ steps.setPath.outputs.appPath }}
-        echo "Building (via make) for ${target}"
-        make ${target}
-        cd ${{ github.workspace }}
+        if [ "${binary}" == "" ]; then
+          err="error: no binary found"
+          echo -e "${err}"
+          echo -e "${err}" >&2
+          echo -e "${err}" >> $GITHUB_STEP_SUMMARY
+        fi
+        echo -e "binary=${binary}"
+        echo "binary=${binary}" >> $GITHUB_OUTPUT
+    #### COMMANDS
     # RUN THE COMMAND
     - name: Generate branch info
       id: safe
       shell: bash
-      env:
-        GHABIN: '${{ steps.info.outputs.binpath }}'
-        RUN_AS_TEST: ${{inputs.test}}
+      env:        
+        LOG_LEVEL: ${{ runner.debug == '1' && "debug" || "error" }}
+        APP_BIN: "${{ steps.binary.outputs.binary }}"
       run: |
-        echo -e "Run branch-name"
-        echo -e "${GHABIN}"
-        ${GHABIN} branch-name \
-          --event_name="${GITHUB_EVENT_NAME}" \
-          --event_data_file="${GITHUB_EVENT_PATH}"
+        echo -e "Run branch-name"        
+        ${APP_BIN} branch-name --event_name="${GITHUB_EVENT_NAME}" --event_data_file="${GITHUB_EVENT_PATH}"
