Convert to golang (#41)
Overhaul the actions to use golang
- Create new commands for each existing python command along with test suite
- Create tests for end to end of semver using the commands to simulate the process of an action
- Convert terraform-version to go from bash
- Create a Makefile to build an executable for the platform it is on
- Create bash script to either fetch the executable from the release, or if the release is not found to checkout of action repository to known folder so it can be built
- Create a pr workflow that builds and attaches an a tarball of executables which can then be used
- Update all relevant actions to use a common process of trying to fetch an existing artifact or building 
a new one from the passed git ref locations and then running the command
- Fix various bugs and issues with differences on the runner compared to local for git config, in particular remotes and ability to checkout to them
- Allow log levels and types to be set by env variables (LOG_LEVEL, LOG_AS, LOG_TO)             
- Push the go tests into a junit file and then use a action to add the test result details to run summary for tracking
- Clean up some input/output variable names and remove exrtas
- Add wrapper around release note generation to handle 125k char limit on release note body

Marking as #minor due to some interface changes on the actions
- branch-name
  - outputs `source_commitish` and `destination_commitish` become `base_commitish` and `head_commitish`  
- create-tag
  - outputs `commitish`, `original_tag_name`, `test` and `latest` are removed
  - outputs `created`, `success` and `regenerated` are added 
- latest-tag
  - input `release_branches` renamed to `release_branch` and presumed to be singular
  - output `latest` renamed to `last_prerelease` to be named more accurately
- next-tag
  - inputs `commitish_a` and `commitish_b` renamed to `base_commitish` and `head_commitish`  to match branch-name
  - outputs ` prerelease_suffix`, `latest_tag`, `last_release`, `with_v`, `commitish_a` and `commitish_b` are removed as they only mirrored input values
- safe-strings
  - outputs `suffix` and `length` removed as only mirrored inputs 
- terraform-version
  - outputs `terraform_directory`, `terraform_versions_file` and `simple_file` remove as they only mirrored inputs

As this is aciton heavy and `act` is not the reliable, I squashed the commits into one as there are dozens relating to small github action tweaks.

Using the go version, a full semver tag process tags under 2 seconds when using an existing artifact and under 25 for a full (uncached) build and then run.

### Example usage
- [Here is a run where this repo uses itself to generate semver tags](https://github.com/ministryofjustice/opg-github-actions/actions/runs/7669757407)
- [External repository using these versions via pre-release](https://github.com/ministryofjustice/opg-github-workflows/actions/runs/7667213390)

### Tests
I've tried to cover as many scenarios end-to-end in the [main_test.go file](https://github.com/ministryofjustice/opg-github-actions/blob/b336def1e854e89e26525e622b546fd698af17cb/go/main_test.go), this can be expanded easily to check any edges cases or possibilities i didnt catch!

### Note 

If you use the pinned commit ref instead of the hash it will force a build as releases are only searchable on tag | name

#major

diff --git a/.github/actions/latest-tag/action.yml b/.github/actions/latest-tag/action.yml
--- a/.github/actions/latest-tag/action.yml
+++ b/.github/actions/latest-tag/action.yml
@@ -10,30 +10,20 @@ inputs:
   branch_name:
     description: "Current branch name"
     default: "beta"
-  release_branches:
-    description: "Branches that would trigger this as a release."
-    default: "main,master"
-  caller_repo_subfolder:
-    description: "Location to checkout active repository into. (Default: ./latest-tag-caller-repository)"
-    default: "./latest-tag-caller-repository"
-  ## Used to capture the intial values before they get overwritten
-  action_ref:
-    description: "Capture the starting value of github.action_ref. DO NOT SET"
-    default: ${{ github.action_ref }}
-  action_repository:
-    description: "Capture the starting value of github.action_repository. DO NOT SET"
-    default: ${{ github.action_repository }}
+  release_branch:
+    description: "Branch that would trigger this as a release."
+    default: "main"
 
 outputs:
   prerelease:
     description: "Inputed prerelease variable."
-    value: ${{ steps.latest.outputs.prerelease_calculated }}
+    value: ${{ steps.latest.outputs.prerelease }}
   prerelease_suffix:
     description: "Inputed prerelease_suffix variable."
     value: ${{ steps.latest.outputs.prerelease_suffix }}
-  latest:
+  last_prerelease:
     description: "Latest tag found"
-    value: ${{steps.latest.outputs.latest}}
+    value: ${{steps.latest.outputs.last_prerelease}}
   last_release:
     description: "Last release tag found"
     value: ${{steps.latest.outputs.last_release}}
@@ -42,52 +32,103 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: "Checkout original repo to set folder"
+    ##### REPEATING BLOCK >>>
+    # Check running as a remote call
+    - name: "Ensure running as remote"
+      if: ${{ github.action_ref == '' }}
+      shell: bash
+      run: |
+        err="ERROR: this composite action must be run via full path (eg ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.3.1)"
+        echo -e "${err}"
+        echo -e "${err}" >&2
+        echo -e "${err}" >> $GITHUB_STEP_SUMMARY
+        exit 1
+    # Use bash shell script to fetch and work out releases    
+    - name: "Get release binary for this runner"
+      shell: bash
+      id: fetch
+      env:
+        GH_TOKEN: ${{ github.token }}
+        GH_ACTION_REPOSITORY: "${{ github.action_repository }}"
+        GH_ACTION_REF: "${{ github.action_ref }}"
+        GH_WORKSPACE: "${{ github.workspace }}"
+        actionsRootDir: "${{ github.action_path }}/../"
+      run: |
+        echo -e "Get release binary"
+        cd ${actionsRootDir}
+        ./release-download.sh 2> $GITHUB_STEP_SUMMARY
+    ## LOCAL BUILD
+    # setup and build locally if the release data is not setup
+    - name: "Setup go"
+      uses: actions/setup-go@v4
+      if: ${{ steps.fetch.outputs.RELEASE == '' }}
+      with:
+        go-version-file: '${{ steps.fetch.outputs.SELF_BUILD }}/./go/go.mod'
+        cache: false
+    - name: Build directly from source
+      id: buildFromSource
+      if: ${{ steps.fetch.outputs.RELEASE == '' }}
+      shell: bash
+      env:
+        buildSource: '${{ steps.fetch.outputs.SELF_BUILD }}'
+        target: '${{ steps.fetch.outputs.TARGET_BUILD }}'
+      run: |
+        echo -e "Build from source"
+        cd ${buildSource}
+        echo -e "Building (with make) for ${target}"        
+        make release
+        release="${buildSource}/go/builds/${target}"
+        echo -e "RELEASE=${release}"
+        echo "RELEASE=${release}" >> $GITHUB_OUTPUT
+    ## DETERMINE BINARY PATH
+    - name: "Determine binary to use"
+      id: binary
+      shell: bash
+      env:
+        direct: ${{ steps.fetch.outputs.RELEASE }}
+        built: ${{ steps.buildFromSource.outputs.RELEASE }}
+      run: |
+        echo -e "Determine binary to use..."
+        binary=""
+        if [ "${direct}" != "" ]; then
+          binary="${direct}"
+        elif [ "${built}" != "" ]; then
+          binary="${built}"
+        fi
+        if [ "${binary}" == "" ]; then
+          err="error: no binary found"
+          echo -e "${err}"
+          echo -e "${err}" >&2
+          echo -e "${err}" >> $GITHUB_STEP_SUMMARY
+        fi
+        echo -e "binary=${binary}"
+        echo "binary=${binary}" >> $GITHUB_OUTPUT
+    ### CHECKOUT
+    # get our the calling repo as we need to access files form there
+    - name: "Checkout calling repository"
       uses: actions/checkout@v4
       with:
         repository: ${{ github.repository }}
         ref: ${{ github.ref }}
-        path: ${{inputs.caller_repo_subfolder}}
-        fetch-tags: true
+        path: '${{ github.workspace}}/_target'
         fetch-depth: 0
-    - name: "Checkout this actions repo into a subfolder at this version"
-      uses: actions/checkout@v4
-      with:
-        repository: ${{ inputs.action_repository }}
-        ref: ${{ inputs.action_ref }}
-        path: ./_ghlatesttagaction
-    - name: pip
+        fetch-tags: true
+    ##### <<< END REPEATING BLOCK 
+    #### COMMANDS
+    - name: "latest-tag" 
+      id: "latest"
       shell: bash
       env:
-        PY_APP_DIR: "${{github.workspace}}/./_ghlatesttagaction/python"
-      run: |
-        echo -e "# pip setup:"
-        echo -e "PY_APP_DIR: ${PY_APP_DIR}"
-        cd ${PY_APP_DIR}
-        pip install -q -r ./requirements.txt
-        pip install -e .
-    - name: Get latest Tag
-      id: latest
-      shell: bash
-      env:
-        PY_APP_DIR: "${{github.workspace}}/./_ghlatesttagaction/python"
-        TARGET_REPO: "${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
-        BRANCH_NAME: ${{inputs.branch_name}}
-        RELEASE_BRANCHES: ${{inputs.release_branches}}
-        PRERELEASE: ${{inputs.prerelease}}
-        PRERELEASE_SUFFIX: ${{inputs.prerelease_suffix}}
-      run: |
-        echo -e "# latest-tag setup:"
-        echo -e "PY_APP_DIR: ${PY_APP_DIR}"
-        echo -e "TARGET_REPO: ${TARGET_REPO}"
-        echo -e "BRANCH_NAME: ${BRANCH_NAME}"
-        echo -e "RELEASE_BRANCHES: ${RELEASE_BRANCHES}"
-        echo -e "PRERELEASE_SUFFIX: ${PRERELEASE_SUFFIX}"
+        GITHUB_TOKEN: ${{ github.token }}
+        LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
+        APP_BIN: "${{ steps.binary.outputs.binary }}"
+        repository: '${{ github.workspace}}/_target'
+        branch: '${{ inputs.branch_name }}'
+        prerelease: '${{ inputs.prerelease }}'
+        prereleaseSuffix: '${{ inputs.prerelease_suffix }}'
+        releaseBranches: '${{ inputs.release_branch }}'
+      run:
+        echo -e "Running latest-tag"
 
-        cd ${PY_APP_DIR}
-        python ./actions/commands/latest_tag.py \
-          --repository_root="${TARGET_REPO}" \
-          --branch_name="${BRANCH_NAME}" \
-          --release_branches="${RELEASE_BRANCHES}" \
-          --prerelease="${PRERELEASE}" \
-          --prerelease_suffix="${PRERELEASE_SUFFIX}"
+        ${APP_BIN} latest-tag --repository="${repository}" --branch="${branch}" --prerelease="${prerelease}" --prerelease-suffix="${prereleaseSuffix}" --release-branches="${releaseBranches}"
+    
diff --git a/.github/workflows/_tests.yml b/.github/workflows/_tests.yml
--- a/.github/workflows/_tests.yml
+++ b/.github/workflows/_tests.yml
@@ -1,14 +1,10 @@
-name: "[Data] Test python code"
+name: "[Data] Test application code"
 
 on:
   workflow_dispatch:
   workflow_call:
 
 jobs:
-  # test terraform-version
-  test_terraform_version:
-    name: "terraform-version"
-    uses: './.github/workflows/test-terraform-version.yml'
 
   # test terraform-workspace-manager
   test_terraform_workspace_manager:
@@ -16,38 +12,46 @@ jobs:
     uses: './.github/workflows/test-terraform-workspace-manager.yml'
     secrets: inherit
 
-  # test terraform-workspace-manager
-  test_semver_tag:
-    name: "semver-tag"
-    uses: './.github/workflows/test-semver-tag.yml'
-
-  # test the python library
-  test_python_app_code:
-    name: "pytest suite"
+  test_go:
+    name: "Go test suite"
     runs-on: ubuntu-latest
     steps:
       - name: "Checkout"
         uses: actions/checkout@v4
-      - name: "Setup python"
-        uses: actions/setup-python@v5
         with:
-          python-version: '3.10'
-      - name: "Setup pip"
-        run: |
-          cd ./python
-          pip install -q -r ./requirements.txt
-          pip install -e .
-      - name: "Setup and run pytest"
-        shell: bash
+          fetch-depth: 0
+          fetch-tags: true
+      - uses: actions/setup-go@v4
+        with:
+          go-version-file: './go/go.mod'        
+          cache: false
+      - name: "Running tests"
         env:
-          RUN_AS_TEST: "true"
+          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
+          LOG_TO: "stdout"
+          GITHUB_TOKEN: ${{ github.token }}
+        run: |          
+          cd ./go
+          go install github.com/jstemmer/go-junit-report/v2@latest
+          echo "" > report.xml
+          go test -v -json -bench -count=5 ./... > test-results.json 2>&1 || true
+          go-junit-report -parser gojson -in test-results.json -out report.xml || true
+
+      - name: Test Report
+        id: report
+        uses: dorny/test-reporter@v1
+        if: always()
+        with:
+          name: Test Results          
+          fail-on-error: false
+          path: ./go/report.xml 
+          reporter: java-junit
+      - name: Output results link
+        run:  |
+          echo "**[Test results](${{steps.report.outputs.url_html}})**" >> $GITHUB_STEP_SUMMARY
+      - name: Test failure
+        if: ${{ steps.report.outputs.conclusion != 'success' }}
         run: |
-          cd ./python
-          git config --global user.name "pytest"
-          git config --global user.email "dummy@dummymail.com"
-          pytest ./tests/
-          echo "$(cat ./branch_name_results.md)" >> $GITHUB_STEP_SUMMARY
-          echo "$(cat ./create_tag_results.md)" >> $GITHUB_STEP_SUMMARY
-          echo "$(cat ./latest_tag_results.md)" >> $GITHUB_STEP_SUMMARY
-          echo "$(cat ./next_tag_results.md)" >> $GITHUB_STEP_SUMMARY
-          echo "$(cat ./safe_strings_results.md)" >> $GITHUB_STEP_SUMMARY
+          echo "Test failed, please see summary: ${{steps.report.outputs.url_html}}"
+          exit 1
+      
