new semver test action

diff --git a/.github/actions/semver-tag/action.yml b/.github/actions/semver-tag/action.yml
--- a/.github/actions/semver-tag/action.yml
+++ b/.github/actions/semver-tag/action.yml
@@ -25,14 +25,7 @@ inputs:
   releases_enabled:
     description: "If set, allows the creation of a release when on a release branch (and not testing)"
     default: "true"
-  ## Used to capture the intial values before they get overwritten
-  action_ref:
-    description: "Capture the starting value of github.action_ref. DO NOT SET"
-    default: ${{ github.action_ref }}
-  action_repository:
-    description: "Capture the starting value of github.action_repository. DO NOT SET"
-    default: ${{ github.action_repository }}
-
+  
 outputs:
   test:
     description: "Inputed test variable."
@@ -46,41 +39,29 @@ outputs:
 
   branch_original:
     description: "Output from branch_name safety check - the branch_name return value"
-    value: ${{ steps.branch_name.outputs.branch_name }}
+    value: ${{ steps.branchname.outputs.branch_name }}
   branch_full_length:
     description: "Output from branch_name safety check - the full_length return value"
-    value: ${{ steps.branch_name.outputs.full_length }}
+    value: ${{ steps.branchname.outputs.full_length }}
   branch_safe:
     description: "Output from branch_name safety check  - the safe return value"
-    value: ${{ steps.branch_name.outputs.safe }}
+    value: ${{ steps.branchname.outputs.safe }}
 
   latest_tag_latest:
     description: "Output from latest_tag - the latest return value"
-    value: ${{ steps.latest_tag.outputs.latest }}
+    value: ${{ steps.latesttag.outputs.latest_prerelease }}
   latest_tag_last_release:
     description: "Output from latest_tag - the last_release value"
-    value: ${{ steps.latest_tag.outputs.last_release }}
+    value: ${{ steps.latesttag.outputs.last_release }}
 
   next_tag:
     description: "Output from next_tag - the next_tag value"
-    value: ${{ steps.next_tag.outputs.next_tag }}
-  next_tag_commitish_a:
-    description: "Output from next_tag - the commitish_a used to look in commits for triggers"
-    value: ""
-  next_tag_commitish_b:
-    description: "Output from next_tag - the commitish_b used to look in commits for triggers"
-    value: ""
-
-  create_tag_latest:
-    description: "Output from create_tag - the latest value"
-    value: ${{ steps.create_tag.outputs.latest }}
+    value: ${{ steps.nexttag.outputs.next_tag }}
+  
   create_tag_created:
-    description: "Output from create_tag - the created value"
-    value: ${{ steps.create_tag.outputs.created }}
-  create_tag_all:
-    description: "Output from create_tag - the all value"
-    value: ${{ steps.create_tag.outputs.all }}
-
+    description: "Output from create_tag - flag if it worked"
+    value: ${{ steps.create_tag.outputs.success }}
+  
   release_id:
     description: "The id of the release if it was created"
     value: ${{steps.create_release.outputs.id}}
@@ -90,115 +71,179 @@ outputs:
 
   created_tag:
     description: "Output from create_tag - the created value"
-    value: ${{ steps.create_tag.outputs.created }}
-
-
+    value: ${{ steps.create_tag.outputs.created_tag }}
 
 runs:
   using: "composite"
   steps:
-    - name: "Checkout this actions repo into a subfolder at this version"
+    #### SETUP ####
+    # Determine if we are being called by self, or by external
+    - name: Setup variables
+      id: setup
+      shell: bash
+      env:
+        ACTION_REPO: "${{ github.action_repository }}"
+        ACTION:REF: "${{ github.action_ref }}"
+        JSON_DEBUG: ${{ toJSON(github) }}
+      run: |
+        echo -e "Setup variables."
+        set -e
+        # self / repo info
+        isSelf="${{ github.repository == 'ministryofjustice/opg-github-actions' }}"
+        echo "isSelf=${isSelf}" >> $GITHUB_OUTPUT
+        echo "actionRepo=${ACTION_REPO}" >> $GITHUB_OUTPUT
+        echo "actionRef=${ACTION_REF}" >> $GITHUB_OUTPUT
+        
+        # build target info
+        gha_os=$(uname | tr '[:upper:]' '[:lower:]')
+        gha_arc=$(uname -m)
+        make_target="${gha_os}_${gha_arc}"
+        echo "target=${make_target}" >> $GITHUB_OUTPUT
+
+        # where to put the target repo
+        echo "targetDir=${{ github.workspace }}/_targetRepo" >> $GITHUB_OUTPUT
+        if [ "${{ runner.debug }}" == "1" ]; then          
+          echo "${JSON_DEBUG}"
+        fi
+
+        if [ "${isSelf}" == "true" ]; then
+          echo -e "Warning: running against self."          
+          path=${{ github.workspace }}/opggha"          
+          echo "path=${path}" >> $GITHUB_OUTPUT
+        elif [ -n "${ACTION_REF}" ]; then   
+          echo -e "Info: running from remote"          
+          path=${{ github.workspace }}/opggha"
+          echo "path=${path}" >> $GITHUB_OUTPUT
+        else
+          echo -e "ERROR: failed to determine action code location"
+          echo -e "ERROR: failed to determine action code location" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+    #### REMOTE CALL ####
+    # If called externally, then checkout self
+    - name: "Checkout action [ ${{ steps.gha.outputs.isSelf }} ]"
+      uses: actions/checkout@v4
+      if: ${{ steps.setup.outputs.isSelf != 'true' }}
+      with:
+        repository: ${{ steps.setup.outputs.actionRepo }}
+        ref: ${{ steps.setup.outputs.actionRef }}
+        path: ${{ steps.setup.outputs.path }}
+    # figure out how to get the artifacts (todo)
+
+    #### SELF CALL ####
+    - name: Setup go
+      if: ${{ steps.setup.outputs.isSelf == 'true' }}
+      uses: actions/setup-go@v4
+      with:
+        go-version-file: '${{ steps.setup.outputs.path }}/go/go.mod'
+        cache-dependency-path: '${{ steps.setup.outputs.path }}/go/go.sum'
+    # run the build 
+    - name: "Build"
+      id: info
+      shell: bash
+      if: ${{ steps.setup.outputs.isSelf == 'true' }}
+      env:
+        target: '${{ steps.info.outputs.target }}'
+        appPath: '${{ steps.setup.outputs.path }}'
+      run: |
+        echo -e "Building"
+        cd ${appPath}
+        echo "Building (via make) for ${target}"
+        make ${target}
+        cd ${{ github.workspace }}
+    #### FETCH THE TARGET REPO INTO A SUB FOLDER
+    - name: "Checkout original repo to set folder"
       uses: actions/checkout@v4
       with:
-        repository: ${{ inputs.action_repository }}
-        ref: ${{ inputs.action_ref }}
-        path: ./_ghsemveraction
-    - name: "Generate safe branch name"
-      id: branch_name
-      uses: ./_ghsemveraction/.github/actions/branch-name
-      with:
-        action_repository: ${{ inputs.action_repository }}
-        action_ref: ${{ inputs.action_ref }}
-    - name: "Find latest tag"
-      id: latest_tag
-      uses: ./_ghsemveraction/.github/actions/latest-tag
-      with:
-          branch_name: ${{steps.branch_name.outputs.branch_name}}
-          release_branches: ${{inputs.release_branch}}
-          prerelease: ${{inputs.prerelease}}
-          prerelease_suffix: ${{steps.branch_name.outputs.safe}}
-          action_repository: ${{ inputs.action_repository }}
-          action_ref: ${{ inputs.action_ref }}
-    - name: "Find next tag"
-      id: next_tag
-      uses: ./_ghsemveraction/.github/actions/next-tag
-      with:
-          prerelease: ${{steps.latest_tag.outputs.prerelease}}
-          prerelease_suffix: ${{steps.latest_tag.outputs.prerelease_suffix}}
-          latest_tag: ${{steps.latest_tag.outputs.latest}}
-          last_release: ${{steps.latest_tag.outputs.last_release}}
-          with_v: ${{inputs.with_v}}
-          commitish_a: ${{steps.branch_name.outputs.source_commitish}}
-          commitish_b: ${{steps.branch_name.outputs.destination_commitish}}
-          default_bump: ${{inputs.default_bump}}
-          action_repository: ${{ inputs.action_repository }}
-          action_ref: ${{ inputs.action_ref }}
-    - name: "Create tag"
-      id: create_tag
-      uses: ./_ghsemveraction/.github/actions/create-tag
-      with:
-          test: ${{inputs.test}}
-          commitish: ${{steps.branch_name.outputs.branch_name}}
-          tag_name: ${{steps.next_tag.outputs.next_tag}}
-          action_repository: ${{ inputs.action_repository }}
-          action_ref: ${{ inputs.action_ref }}
-
-    # if the branch is release branch, releases are enabled and this is not a test
-    - id: create_release
-      name: Create release
-      if: ${{ ( contains(github.ref, inputs.release_branch) ) &&
-              ( inputs.releases_enabled == 'true' ) &&
-              ( inputs.test == '')  }}
-      uses: ncipollo/release-action@v1.13.0
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
-      with:
-        tag: ${{ steps.create_tag.outputs.created }}
-        name: ${{ steps.create_tag.outputs.created }}
-        draft: false
-        prerelease: false
-        generateReleaseNotes: true
-
-    - name: summary
+        repository: ${{ github.repository }}
+        ref: ${{ github.ref }}
+        path: ${{ steps.setup.ouputs.targetDir }}
+        fetch-tags: true
+        fetch-depth: 0
+    #### COMMANDS
+    # Get branch name info
+    - name: "branch-name"
+      id: branchname
       shell: bash
-      if: ${{ (always()) && (inputs.show_verbose_summary == '') }}
+      env:        
+        RUN_AS_TEST: ${{inputs.test}}
+        appPath: '${{ steps.setup.outputs.path }}'
+        binPath: '${{ steps.setup.outputs.path }}/go/builds/${{ steps.setup.outputs.target }}'
       run: |
-        set -eo pipefail
-        echo "### Semver tag summary" >> $GITHUB_STEP_SUMMARY
-        echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
-        echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
-        echo "| **Created Tag** | **${{ steps.create_tag.outputs.created }}** |"  >> $GITHUB_STEP_SUMMARY
-
-        if [ -n "${{ steps.create_release.outputs.id }}" ]; then
-          echo "| **Release** | [${{ steps.create_release.outputs.id }}](${{ steps.create_release.outputs.html_url }}) |"  >> $GITHUB_STEP_SUMMARY
-        fi
-
-
-    - name: Verbose summary
+        ${binPath} branch-name \
+          --event-name="${GITHUB_EVENT_NAME}" \
+          --event-data-file="${GITHUB_EVENT_PATH}"
+    # latest tag
+    - name: "latest-tag"
+      id: latesttag
       shell: bash
-      if: ${{ (always()) && (inputs.show_verbose_summary != '') }}
+      env:        
+        RUN_AS_TEST: ${{ inputs.test }}
+        appPath: '${{ steps.setup.outputs.path }}'
+        binPath: '${{ steps.setup.outputs.path }}/go/builds/${{ steps.setup.outputs.target }}'
+        repo: '${{ steps.setup.outputs.targetDir }}'
+        branch: '${{ steps.branchname.outputs.branch_name }}'
+        prerelease: '${{ inputs.prerelease }}'
+        prereleaseSuffix: '${{ steps.branchname.outputs.safe }}'
+        releaseBranch: '${{ inputs.release_branch }}'
       run: |
-        set -eo pipefail
-        echo "### Semver tag summary" >> $GITHUB_STEP_SUMMARY
-        echo "| Stage | Variable | Value |" >> $GITHUB_STEP_SUMMARY
-        echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Branch | original | ${{ steps.branch_name.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Branch | safe | ${{ steps.branch_name.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Branch | full_length | ${{ steps.branch_name.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
+        ${binPath} latest-tag \
+          --repository="${repo}" \
+          --branch="${branch}" \
+          --prerelease="${prerelease}" \
+          --prerelease-suffix="${prereleaseSuffix}" \
+          --release-branches="${releaseBranch}"
+   # next tag
+    - name: "next-tag"
+      id: nexttag
+      shell: bash
+      env:        
+        RUN_AS_TEST: ${{ inputs.test }}
+        appPath: '${{ steps.setup.outputs.path }}'
+        binPath: '${{ steps.setup.outputs.path }}/go/builds/${{ steps.setup.outputs.target }}'
+        repo: '${{ steps.setup.outputs.targetDir }}'
+        branch: '${{ steps.branchname.outputs.branch_name }}'
+        prerelease: '${{ steps.latesttag.outputs.prerelease }}'
+        prereleaseSuffix: '${{ steps.latesttag.outputs.prerelease_suffix }}'        
+        baseRef: '${{ steps.branchname.outputs.base_commitish }}'
+        headRef: '${{ steps.branchname.outputs.head_commitish }}'
+        lastRelease: '${{ steps.latesttag.outputs.last_release }}'
+        lastPreelease: '${{ steps.latesttag.outputs.last_prerelease }}'
+        withV: '${{ inputs.with_v }}'
+        defaultBump: '${{ inputs.default_bump }}'
+      run: |
+        ${binPath} next-tag \          
+          --repository="${repo}" \
+          --base="${baseRef}" \
+          --head="${headRef}" \
+          --prerelease="${prerelease}" \
+          --prerelease-suffix="${prereleaseSuffix}" \
+          --last-release="${lastRelease}" \
+          --last-prerelease="${lastPreelease}" \
+          --with-v="${withV}" \
+          --default-bump="${defaultBump}"
+   # create tag
+    - name: "create-tag"
+      id: createtag
+      shell: bash
+      env:        
+        RUN_AS_TEST: ${{ inputs.test }}
+        appPath: '${{ steps.setup.outputs.path }}'
+        binPath: '${{ steps.setup.outputs.path }}/go/builds/${{ steps.setup.outputs.target }}'
+        repo: '${{ steps.setup.outputs.targetDir }}'
+        commitish: '${{ steps.branchname.outputs.branch_name }}'
+        tagName: '${{ steps.nexttag.outputs.next_tag }}'
+        prereleaseSuffix: '${{ steps.latesttag.outputs.prerelease_suffix }}'                
+      run: |
+        ${binPath} create-tag \          
+          --repository="${repo}" \
+          --commitish="${commitish}" \
+          --tag-name="${tagName}" \
+          --regen="true" \
+          --push="false" 
 
-        echo "| Latest Tag | latest | ${{ steps.latest_tag.outputs.latest }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Latest Tag | last_release | ${{ steps.latest_tag.outputs.last_release }} |"  >> $GITHUB_STEP_SUMMARY
 
-        echo "| Next Tag | last_release | ${{ steps.next_tag.outputs.last_release }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Next Tag | latest_tag | ${{ steps.next_tag.outputs.latest_tag }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Next Tag | commitish_a | ${{ steps.next_tag.outputs.commitish_a }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Next Tag | commitish_b | ${{ steps.next_tag.outputs.commitish_b }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Next Tag | next_tag | ${{ steps.next_tag.outputs.next_tag }} |"  >> $GITHUB_STEP_SUMMARY
+          
 
-        echo "| Create Tag | latest | ${{ steps.create_tag.outputs.latest }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| Create Tag | test | ${{ steps.create_tag.outputs.test }} |"  >> $GITHUB_STEP_SUMMARY
-        echo "| **Create Tag** | **created** | **${{ steps.create_tag.outputs.created }}** |"  >> $GITHUB_STEP_SUMMARY
-
-        if [ -n "${{ steps.create_release.outputs.id }}" ]; then
-          echo "| **Release** | **URL** | **[${{ steps.create_release.outputs.id }}](${{ steps.create_release.outputs.html_url }})** |"  >> $GITHUB_STEP_SUMMARY
-        fi
+        
+          
