turn other tests back on

diff --git a/.github/workflows/test-next-tag.yml b/.github/workflows/test-next-tag.yml
--- a/.github/workflows/test-next-tag.yml
+++ b/.github/workflows/test-next-tag.yml
@@ -38,40 +38,40 @@ jobs:
           latest_tag: "v1.5.0-moreactions.1"
           last_release: "v1.4.0"
           with_v: true
-      # - id: test1_2
-      #   name: "1.2 Test major version bump as an existing prerelease"
-      #   uses: './.github/actions/next-tag'
-      #   with: 
-      #     test: true
-      #     test_file: "./tests/majors.txt"
-      #     prerelease: true
-      #     prerelease_suffix: "moreactions"
-      #     latest_tag: "v2.0.0-moreactions.0"
-      #     last_release: "v1.4.0"
-      # - id: test1_3
-      #   name: "1.3 Test major version bump without latest_tag as a prerelease"
-      #   uses: './.github/actions/next-tag'
-      #   with: 
-      #     test: true
-      #     test_file: "./tests/majors.txt"
-      #     prerelease: true
-      #     prerelease_suffix: "moreactions"
-      #     last_release: "v1.4.0"
-      # - id: test1_4
-      #   name: "1.4 Test major version bump without latest_tag as a release"
-      #   uses: './.github/actions/next-tag'
-      #   with: 
-      #     test: true
-      #     test_file: "./tests/majors.txt"
-      #     prerelease_suffix: "moreactions"
-      #     last_release: "v1.4.0"
-      # - id: test1_5
-      #   name: "1.5 Test major version from empty"
-      #   uses: './.github/actions/next-tag'
-      #   with: 
-      #     test: true
-      #     test_file: "./tests/majors.txt"
-      #     prerelease_suffix: "moreactions"
+      - id: test1_2
+        name: "1.2 Test major version bump as an existing prerelease"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/majors.txt"
+          prerelease: true
+          prerelease_suffix: "moreactions"
+          latest_tag: "v2.0.0-moreactions.0"
+          last_release: "v1.4.0"
+      - id: test1_3
+        name: "1.3 Test major version bump without latest_tag as a prerelease"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/majors.txt"
+          prerelease: true
+          prerelease_suffix: "moreactions"
+          last_release: "v1.4.0"
+      - id: test1_4
+        name: "1.4 Test major version bump without latest_tag as a release"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/majors.txt"
+          prerelease_suffix: "moreactions"
+          last_release: "v1.4.0"
+      - id: test1_5
+        name: "1.5 Test major version from empty"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/majors.txt"
+          prerelease_suffix: "moreactions"
       - id: test_results
         name: Test results
         run: |
@@ -85,31 +85,31 @@ jobs:
           echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
           echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
           echo "| 1. | ${t1_1} | ${{steps.test1_1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          # echo "| 2. | ${t1_2} | ${{steps.test1_2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          # echo "| 3. | ${t1_3} | ${{steps.test1_3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          # echo "| 4. | ${t1_4} | ${{steps.test1_4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          # echo "| 5. | ${t1_5} | ${{steps.test1_5.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 2. | ${t1_2} | ${{steps.test1_2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 3. | ${t1_3} | ${{steps.test1_3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 4. | ${t1_4} | ${{steps.test1_4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 5. | ${t1_5} | ${{steps.test1_5.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
           
           if [ "${{steps.test1_1.outputs.next_tag}}" != "${t1_1}" ]; then
             echo "test 1.1 failed"
             exit 1
           fi
-          # if [ "${{steps.test1_2.outputs.next_tag}}" != "${t1_2}" ]; then
-          #   echo "test 1.2 failed"
-          #   exit 1
-          # fi
-          # if [ "${{steps.test1_3.outputs.next_tag}}" != "${t1_3}" ]; then
-          #   echo "test 1.3 failed"
-          #   exit 1
-          # fi
-          # if [ "${{steps.test1_4.outputs.next_tag}}" != "${t1_4}" ]; then
-          #   echo "test 1.4 failed"
-          #   exit 1
-          # fi
-          # if [ "${{steps.test1_5.outputs.next_tag}}" != "${t1_5}" ]; then
-          #   echo "test 1.5 failed"
-          #   exit 1
-          # fi
+          if [ "${{steps.test1_2.outputs.next_tag}}" != "${t1_2}" ]; then
+            echo "test 1.2 failed"
+            exit 1
+          fi
+          if [ "${{steps.test1_3.outputs.next_tag}}" != "${t1_3}" ]; then
+            echo "test 1.3 failed"
+            exit 1
+          fi
+          if [ "${{steps.test1_4.outputs.next_tag}}" != "${t1_4}" ]; then
+            echo "test 1.4 failed"
+            exit 1
+          fi
+          if [ "${{steps.test1_5.outputs.next_tag}}" != "${t1_5}" ]; then
+            echo "test 1.5 failed"
+            exit 1
+          fi
           
 
           
