add in minors

diff --git a/.github/workflows/test-next-tag.yml b/.github/workflows/test-next-tag.yml
--- a/.github/workflows/test-next-tag.yml
+++ b/.github/workflows/test-next-tag.yml
@@ -18,17 +18,94 @@ permissions:
 
 
 jobs:
-  test:
+  minors:
     runs-on: 'ubuntu-latest'
-    name: "Test next-tag"
+    name: "Test next-tag minors"
     steps:
-      - 
+      - name: "Checkout"
         uses: actions/checkout@v4
         with:
           repository: ${{ github.repository }}
           ref: ${{ github.ref }}
-      - id: test1_1
-        name: "1.1 Test major version bump as a new prerelease (with v)"
+      - id: test1
+        name: "1. Test minor version bump as an existing prerelease"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/minors.txt"
+          prerelease: true
+          prerelease_suffix: "moreactions"
+          latest_tag: "v1.5.0-moreactions.0"
+          last_release: "v1.4.0"
+      - id: test2
+        name: "2. Test minor version bump prerelease without latest_tag"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/minors.txt"
+          prerelease: true
+          prerelease_suffix: "moreactions"
+          last_release: "v1.4.0"
+      - id: test3
+        name: "3. Test minor version bump as a release"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/minors.txt"
+          prerelease_suffix: "moreactions"
+          latest_release: "v1.5.0-moreactions.0"
+          last_release: "v1.4.0"
+      - id: test4
+        name: "4. Test minor version bump without latest_tag as a release"
+        uses: './.github/actions/next-tag'
+        with: 
+          test: true
+          test_file: "./tests/minors.txt"
+          prerelease_suffix: "moreactions"
+      - id: test_results
+        name: Test results [Majors]
+        run: |
+          t1="1.5.0-moreactions.1"
+          t2="1.5.0-moreactions.0"
+          t3="1.5.0"
+          t4="0.1.0"
+          
+          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
+          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
+          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
+          echo "| 1. | ${t1} | ${{steps.test1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 2. | ${t2} | ${{steps.test2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 3. | ${t3} | ${{steps.test3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 4. | ${t4} | ${{steps.test4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          
+          if [ "${{steps.test1.outputs.next_tag}}" != "${t1}" ]; then
+            echo "test 1.1 failed"
+            exit 1
+          fi
+          if [ "${{steps.test2.outputs.next_tag}}" != "${t2}" ]; then
+            echo "test 1.2 failed"
+            exit 1
+          fi
+          if [ "${{steps.test3.outputs.next_tag}}" != "${t3}" ]; then
+            echo "test 1.3 failed"
+            exit 1
+          fi
+          if [ "${{steps.test4.outputs.next_tag}}" != "${t4}" ]; then
+            echo "test 1.4 failed"
+            exit 1
+          fi
+          
+  majors:
+    runs-on: 'ubuntu-latest'
+    name: "Test next-tag [majors]"
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository }}
+          ref: ${{ github.ref }}
+      - id: test1
+        name: "1. Test major version bump as a new prerelease (with v)"
         uses: './.github/actions/next-tag'
         with: 
           test: true
@@ -38,8 +115,8 @@ jobs:
           latest_tag: "v1.5.0-moreactions.1"
           last_release: "v1.4.0"
           with_v: true
-      - id: test1_2
-        name: "1.2 Test major version bump as an existing prerelease"
+      - id: test2
+        name: "2. Test major version bump as an existing prerelease"
         uses: './.github/actions/next-tag'
         with: 
           test: true
@@ -48,8 +125,8 @@ jobs:
           prerelease_suffix: "moreactions"
           latest_tag: "v2.0.0-moreactions.0"
           last_release: "v1.4.0"
-      - id: test1_3
-        name: "1.3 Test major version bump without latest_tag as a prerelease"
+      - id: test3
+        name: "3. Test major version bump without latest_tag as a prerelease"
         uses: './.github/actions/next-tag'
         with: 
           test: true
@@ -57,56 +134,56 @@ jobs:
           prerelease: true
           prerelease_suffix: "moreactions"
           last_release: "v1.4.0"
-      - id: test1_4
-        name: "1.4 Test major version bump without latest_tag as a release"
+      - id: test4
+        name: "4. Test major version bump without latest_tag as a release"
         uses: './.github/actions/next-tag'
         with: 
           test: true
           test_file: "./tests/majors.txt"
           prerelease_suffix: "moreactions"
           last_release: "v1.4.0"
-      - id: test1_5
-        name: "1.5 Test major version from empty"
+      - id: test5
+        name: "5. Test major version from empty"
         uses: './.github/actions/next-tag'
         with: 
           test: true
           test_file: "./tests/majors.txt"
           prerelease_suffix: "moreactions"
       - id: test_results
-        name: Test results
+        name: Test results [Major]
         run: |
-          t1_1="v2.0.0-moreactions.0"
-          t1_2="2.0.0-moreactions.1"
-          t1_3="2.0.0-moreactions.0"
-          t1_4="2.0.0"
-          t1_5="1.0.0"
+          t1="v2.0.0-moreactions.0"
+          t2="2.0.0-moreactions.1"
+          t3="2.0.0-moreactions.0"
+          t4="2.0.0"
+          t5="1.0.0"
           
           echo "### Test Information" >> $GITHUB_STEP_SUMMARY
           echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
           echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
-          echo "| 1. | ${t1_1} | ${{steps.test1_1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          echo "| 2. | ${t1_2} | ${{steps.test1_2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          echo "| 3. | ${t1_3} | ${{steps.test1_3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          echo "| 4. | ${t1_4} | ${{steps.test1_4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
-          echo "| 5. | ${t1_5} | ${{steps.test1_5.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 1. | ${t1} | ${{steps.test1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 2. | ${t2} | ${{steps.test2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 3. | ${t3} | ${{steps.test3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 4. | ${t4} | ${{steps.test4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
+          echo "| 5. | ${t5} | ${{steps.test5.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
           
-          if [ "${{steps.test1_1.outputs.next_tag}}" != "${t1_1}" ]; then
+          if [ "${{steps.test1.outputs.next_tag}}" != "${t1}" ]; then
             echo "test 1.1 failed"
             exit 1
           fi
-          if [ "${{steps.test1_2.outputs.next_tag}}" != "${t1_2}" ]; then
+          if [ "${{steps.test2.outputs.next_tag}}" != "${t2}" ]; then
             echo "test 1.2 failed"
             exit 1
           fi
-          if [ "${{steps.test1_3.outputs.next_tag}}" != "${t1_3}" ]; then
+          if [ "${{steps.test3.outputs.next_tag}}" != "${t3}" ]; then
             echo "test 1.3 failed"
             exit 1
           fi
-          if [ "${{steps.test1_4.outputs.next_tag}}" != "${t1_4}" ]; then
+          if [ "${{steps.test4.outputs.next_tag}}" != "${t4}" ]; then
             echo "test 1.4 failed"
             exit 1
           fi
-          if [ "${{steps.test1_5.outputs.next_tag}}" != "${t1_5}" ]; then
+          if [ "${{steps.test5.outputs.next_tag}}" != "${t5}" ]; then
             echo "test 1.5 failed"
             exit 1
           fi
